### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ghost** [jwagner/addresscloud#1]
@jwagner Thank you for your hard work,

I am new to webgl, some questions:
- Can I visualize my own data using this code?
- what should be the input data structure, can you upload a sample
- How can I visualize the input data

**Comment by jwagner** [comment]
Neither does the license permit you to use this code to visualize your own data nor should you. Use a library that is fit for purpose. https://plot.ly/javascript/ is generally a good place to start.

This repository here is just for those curious how that demo was coded.
